### ISSUE TITLE
If "publish_to" is ommited then "Cannot achieve desired consistency level with 0 nodes" error appears

### ISSUE THREAD

**Issue by smilesrg** [SoCloz/NsqBundle#2]
If `publish_to` is ommited then `Cannot achieve desired consistency level with 0 nodes` error appears. It seems that `lookupd_hosts`

``` yaml
# app/config.yml

socloz_nsq:
  lookupd_hosts: ["localhost:4161"] 
  topics:
    foo:
      publish_to: [localhost] # if this option is ommited, lookupd_hosts is not used somewhy
```
